"""Added type to Notification table

Revision ID: 0b932d55ed18
Revises: 13233791a908
Create Date: 2026-03-10 09:39:15.963510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0b932d55ed18'
down_revision: Union[str, Sequence[str], None] = '13233791a908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create the enum type in the database first
    notification_type_enum = postgresql.ENUM(
        'WELCOME', 
        'GOAL_CREATED', 
        'GOAL_MILESTONE', 
        'GOAL_COMPLETED', 
        'BUDGET_SUMMARY', 
        'BUDGET_EXCEEDED', 
        name='notificationtype'
    )
    notification_type_enum.create(op.get_bind())

    # 2. Now add the column (this is the line that was failing)
    op.add_column('notification', sa.Column('type', notification_type_enum, nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'type')
    # ### end Alembic commands ###
    # 2. Drop the enum type from the database
    postgresql.ENUM(name='notificationtype').drop(op.get_bind())
