"""Created rollover model and added is_surplus to expense model

Revision ID: 0e4c76650be5
Revises: c455bb1a0d28
Create Date: 2026-04-09 19:26:43.615094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e4c76650be5'
down_revision: Union[str, Sequence[str], None] = 'c455bb1a0d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rollover',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('source_month', sa.Integer(), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rollover_id'), 'rollover', ['id'], unique=False)
    op.create_index(op.f('ix_rollover_user_id'), 'rollover', ['user_id'], unique=False)
    op.add_column('expense', sa.Column('is_surplus', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'is_surplus')
    op.drop_index(op.f('ix_rollover_user_id'), table_name='rollover')
    op.drop_index(op.f('ix_rollover_id'), table_name='rollover')
    op.drop_table('rollover')
    # ### end Alembic commands ###
