"""updates

Revision ID: 19b0dce87e97
Revises: 7c91a16a16aa
Create Date: 2026-04-11 17:20:57.398730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19b0dce87e97'
down_revision: Union[str, Sequence[str], None] = '7c91a16a16aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_insights_id'), 'user_insights', ['id'], unique=False)
    op.create_index(op.f('ix_user_insights_user_id'), 'user_insights', ['user_id'], unique=False)
    op.drop_index(op.f('ix_userinsights_id'), table_name='userinsights')
    op.drop_index(op.f('ix_userinsights_user_id'), table_name='userinsights')
    op.drop_table('userinsights')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userinsights',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('userinsights_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('userinsights_pkey'))
    )
    op.create_index(op.f('ix_userinsights_user_id'), 'userinsights', ['user_id'], unique=False)
    op.create_index(op.f('ix_userinsights_id'), 'userinsights', ['id'], unique=False)
    op.drop_index(op.f('ix_user_insights_user_id'), table_name='user_insights')
    op.drop_index(op.f('ix_user_insights_id'), table_name='user_insights')
    op.drop_table('user_insights')
    # ### end Alembic commands ###
