"""added is_toasted to notifications model

Revision ID: 2d2da1308832
Revises: 19b0dce87e97
Create Date: 2026-04-12 14:38:00.071750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d2da1308832'
down_revision: Union[str, Sequence[str], None] = '19b0dce87e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('is_toasted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_notification_is_toasted'), 'notification', ['is_toasted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_is_toasted'), table_name='notification')
    op.drop_column('notification', 'is_toasted')
    # ### end Alembic commands ###
