"""added budgetbucket and budgetcategory

Revision ID: 33f9be59b534
Revises: 148e45ac9dcd
Create Date: 2026-03-05 19:37:26.746748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33f9be59b534'
down_revision: Union[str, Sequence[str], None] = '148e45ac9dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_buckets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Enum('NEEDS', 'WANTS', 'SAVINGS', name='allocationname'), nullable=False),
    sa.Column('percentage_allocation', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='unique_user_allocation')
    )
    op.create_index(op.f('ix_budget_buckets_id'), 'budget_buckets', ['id'], unique=False)
    op.create_index(op.f('ix_budget_buckets_name'), 'budget_buckets', ['name'], unique=False)
    op.create_table('budget_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('bucket_id', sa.Uuid(), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['budget_buckets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_id', 'name', name='unique_bucket_category')
    )
    op.create_index(op.f('ix_budget_categories_id'), 'budget_categories', ['id'], unique=False)
    op.create_index(op.f('ix_budget_categories_name'), 'budget_categories', ['name'], unique=False)
    op.drop_index(op.f('ix_allocation_id'), table_name='allocation')
    op.drop_index(op.f('ix_allocation_user_id'), table_name='allocation')
    op.drop_table('allocation')
    op.add_column('expense', sa.Column('category_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_expense_category'), table_name='expense')
    op.drop_index(op.f('ix_expense_user_id'), table_name='expense')
    op.create_foreign_key(None, 'expense', 'budget_categories', ['category_id'], ['id'])
    op.drop_column('expense', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.create_index(op.f('ix_expense_user_id'), 'expense', ['user_id'], unique=False)
    op.create_index(op.f('ix_expense_category'), 'expense', ['category'], unique=False)
    op.drop_column('expense', 'category_id')
    op.create_table('allocation',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('needs_percent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wants_percent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('savings_percent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('allocation_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('allocation_pkey'))
    )
    op.create_index(op.f('ix_allocation_user_id'), 'allocation', ['user_id'], unique=True)
    op.create_index(op.f('ix_allocation_id'), 'allocation', ['id'], unique=False)
    op.drop_index(op.f('ix_budget_categories_name'), table_name='budget_categories')
    op.drop_index(op.f('ix_budget_categories_id'), table_name='budget_categories')
    op.drop_table('budget_categories')
    op.drop_index(op.f('ix_budget_buckets_name'), table_name='budget_buckets')
    op.drop_index(op.f('ix_budget_buckets_id'), table_name='budget_buckets')
    op.drop_table('budget_buckets')
    # ### end Alembic commands ###
