"""Added title and reference_id to notification table

Revision ID: 38fb42791930
Revises: 0b932d55ed18
Create Date: 2026-03-10 11:10:50.102456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '38fb42791930'
down_revision: Union[str, Sequence[str], None] = '0b932d55ed18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('notification', sa.Column('reference_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'reference_id')
    op.drop_column('notification', 'title')
    # ### end Alembic commands ###
