"""update

Revision ID: 3eb82c5e30bb
Revises: 717299eeae6f
Create Date: 2026-03-07 12:03:32.706092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3eb82c5e30bb'
down_revision: Union[str, Sequence[str], None] = '717299eeae6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budget_categories', 'monthly_limit',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_column('income', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('budget_categories', 'monthly_limit',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
