"""Added indexes

Revision ID: 5950a2bf5e61
Revises: f10c94cc28e4
Create Date: 2026-03-07 20:00:42.219388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5950a2bf5e61'
down_revision: Union[str, Sequence[str], None] = 'f10c94cc28e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_expense_category_id'), 'expense', ['category_id'], unique=False)
    op.create_index(op.f('ix_expense_date'), 'expense', ['date'], unique=False)
    op.create_index(op.f('ix_expense_user_id'), 'expense', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_user_id'), table_name='expense')
    op.drop_index(op.f('ix_expense_date'), table_name='expense')
    op.drop_index(op.f('ix_expense_category_id'), table_name='expense')
    # ### end Alembic commands ###
