"""Added name to User Model

Revision ID: 5976b9b6019f
Revises: a9a8dd6de88d
Create Date: 2026-03-14 13:00:02.960551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5976b9b6019f'
down_revision: Union[str, Sequence[str], None] = 'a9a8dd6de88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
