"""updated currency field in user model

Revision ID: 717299eeae6f
Revises: e1772b57db7a
Create Date: 2026-03-06 18:04:55.538588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '717299eeae6f'
down_revision: Union[str, Sequence[str], None] = 'e1772b57db7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Create the new Enum type
    op.execute("CREATE TYPE frequencystatus AS ENUM ('WEEKLY', 'BIWEEKLY', 'MONTHLY', 'YEARLY')")
    
    # 2. Alter the column and cast the data
    # We cast to text first so Postgres can map the strings to the new type
    op.execute(
        "ALTER TABLE income ALTER COLUMN frequency TYPE frequencystatus "
        "USING frequency::text::frequencystatus"
    )
    
    # 3. Drop the old Enum type if it's no longer used
    op.execute("DROP TYPE frequency_status")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('income', 'frequency',
               existing_type=sa.Enum('WEEKLY', 'BIWEEKLY', 'MONTHLY', 'YEARLY', name='frequencystatus'),
               type_=postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='frequency_status'),
               existing_nullable=False)
    # ### end Alembic commands ###
