"""Added title and notes to expense table

Revision ID: a9a8dd6de88d
Revises: 38fb42791930
Create Date: 2026-03-12 14:31:05.282646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a9a8dd6de88d'
down_revision: Union[str, Sequence[str], None] = '38fb42791930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('expense', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('expense', 'description')
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_is_read'), 'notification', ['is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_is_read'), table_name='notification')
    op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
    op.add_column('expense', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('expense', 'notes')
    op.drop_column('expense', 'title')
    # ### end Alembic commands ###
