"""add user insights table

Revision ID: b59503f31ff0
Revises: 0e4c76650be5
Create Date: 2026-04-10 22:38:09.483138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b59503f31ff0'
down_revision: Union[str, Sequence[str], None] = '0e4c76650be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userinsights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userinsights_id'), 'userinsights', ['id'], unique=False)
    op.create_index(op.f('ix_userinsights_user_id'), 'userinsights', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userinsights_user_id'), table_name='userinsights')
    op.drop_index(op.f('ix_userinsights_id'), table_name='userinsights')
    op.drop_table('userinsights')
    # ### end Alembic commands ###
