"""Removed is_default from category

Revision ID: b66ca6bea542
Revises: 5976b9b6019f
Create Date: 2026-03-21 22:39:01.655061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b66ca6bea542'
down_revision: Union[str, Sequence[str], None] = '5976b9b6019f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_categories', 'is_default')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_categories', sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
