"""Updated goal table

Revision ID: ba004b8357f0
Revises: 5950a2bf5e61
Create Date: 2026-03-09 13:59:25.924468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba004b8357f0'
down_revision: Union[str, Sequence[str], None] = '5950a2bf5e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('goal', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.alter_column('goal', 'target_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('goal', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_goal_type'), table_name='goal')
    op.create_index(op.f('ix_goal_name'), 'goal', ['name'], unique=False)
    op.drop_column('goal', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_goal_name'), table_name='goal')
    op.create_index(op.f('ix_goal_type'), 'goal', ['type'], unique=False)
    op.alter_column('goal', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('goal', 'target_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('goal', 'is_completed')
    op.drop_column('goal', 'name')
    # ### end Alembic commands ###
