"""Updated monthly_limit to default none in budgetcategory

Revision ID: c455bb1a0d28
Revises: d8fb89e83bfa
Create Date: 2026-04-08 12:39:16.011002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c455bb1a0d28'
down_revision: Union[str, Sequence[str], None] = 'd8fb89e83bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
