"""Added percentage_allocation to budget_category

Revision ID: d8fb89e83bfa
Revises: b66ca6bea542
Create Date: 2026-04-08 11:15:30.516656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd8fb89e83bfa'
down_revision: Union[str, Sequence[str], None] = 'b66ca6bea542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_categories', sa.Column('percentage_allocation', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget_categories', 'percentage_allocation')
    # ### end Alembic commands ###
