"""updated expense model field from spent_at to date

Revision ID: f10c94cc28e4
Revises: 3eb82c5e30bb
Create Date: 2026-03-07 18:25:48.838147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f10c94cc28e4'
down_revision: Union[str, Sequence[str], None] = '3eb82c5e30bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('date', sa.DateTime(), nullable=False))
    op.alter_column('expense', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('expense', 'spent_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('spent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('expense', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('expense', 'date')
    # ### end Alembic commands ###
